# Generated by Django 3.0.5 on 2020-06-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='image',
            field=models.ImageField(default="home/images/no-img.jpg'", upload_to='home/images'),
        ),
    ]
