# Generated by Django 3.0.5 on 2020-06-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200607_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
