# Generated by Django 3.0.5 on 2020-06-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200607_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='image',
            field=models.FileField(default='', upload_to='media/'),
        ),
    ]
