# Generated by Django 3.0.5 on 2020-06-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200607_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='image',
            field=models.FileField(upload_to='media'),
        ),
    ]
